version: '3.9'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 looktvps.asgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db



  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - web


